# Generated by Django 4.1.6 on 2023-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft17', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='curr_state',
            field=models.IntegerField(choices=[(0, 'Reset Game'), (1, 'Start Game'), (2, 'Place Bet'), (3, 'Deal Players'), (4, 'Deal Dealer'), (5, 'Player Turn'), (6, 'Player Score'), (7, 'Dealer Turn'), (8, 'Dealer Score'), (9, 'Compute Scores')], default=1),
        ),
    ]
